### ISSUE TITLE
Weird behavior on IE 11.

### ISSUE THREAD

**Issue by RakeshChouhan** [sergi/virtual-list#5]
I tried the 1 million sample code on IE 11, it is only showing 30 items in the list but on Chrome it is working fine.

**Comment by RakeshChouhan** [comment]
Any update on this ??

**Comment by nasreddineskandrani** [comment]
with i.e. 11 or Edge, i am also having a problem with a lot of rows > 1000000 its stuck at 51000 
i am debugging that give me some time to find a fix

**Comment by nasreddineskandrani** [comment]
after some research i found that IE10 even IE11 in my test has a maximum y scroll value. So this approach to do virtual paging is not good for IE edge...

**Comment by RakeshChouhan** [comment]
Ok Thank you very much ! 

I have found a work around for this, to get less on UI. Now I am not fetching more than 5000 record on UI and application works smoothly. I am closing this issue because expecting from IE is useless.
